---
title: "Example"
author: "Anonymous Author(s)"
date: "3 June 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries and Functions

```{r}
library(pracma)
library(igraph)
source('functions.R')
```

Generate the data as follows. 

```{r}
k=9
p=2
x=seq(0,1,length.out = 3)
y=x
z=outer(x,y)
M=matrix(0,9,2)
for(i in 1:3){
  for(j in 1:3){
    M[3*(i-1)+j,]=c(x[i],y[j])
  }
}
X=data_generate(600,M,rep(1/k,k),0.05,0.05)
ground_truth=X$label
X=X$data
X=rbind(X,rand(20,2)*50)
```

Plotting the data.

```{r}
plot(X,xlab='x',ylab='y',main='Scatterplot of the data')
```

# MOMPKM

```{r}
l1=MOMPKM(X,k=9,L=41,eta=1.02,alpha=1,verbose=T,tmax=200)
```

```{r}
plot(X,col=l1$label, pch = l1$label + 10 ,
     xlim =c(-0.2,1.2),ylim=c(-0.2,1.2), 
     xlab='x',ylab='y',main='Scatterplot of the data, color-coded with partition by MOMPKM')
```

Compare the ground truth and the obtained partition through ARI. 

```{r}
compare(ground_truth,l1$label[1:600],'adjusted.rand')
```
Results in perfect clusterng!

# PKM


```{r}
l2=power.k.means(X,k=9)
plot(X,col=l2$label, pch = l1$label + 10, 
     xlim =c(-0.2,1.2),ylim=c(-0.2,1.2), 
     xlab='x',ylab='y',main='Scatterplot of the data, color-coded with partition by PKM')
```

Compare the ground truth and the obtained partition through ARI. 

```{r}
compare(ground_truth,l2$label[1:600],'adjusted.rand')
```

Imperfect clustering even in this simple setting!
